# Generated by Django 4.0.5 on 2022-06-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_tagrecipe_recipe_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'ordering': ['recipe'], 'verbose_name': 'Тэг в рецепте', 'verbose_name_plural': 'Тэги в рецептах'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Тэг'),
        ),
    ]
