# Generated by Django 4.0.5 on 2022-06-29 11:49

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[recipes.validators.validate_color_tag], verbose_name='Цвет'),
        ),
    ]
